export const data = [
    {
        id: 1,
        name: 'Alexander Monaco',
        location: 'Jalan Sudirman',
        createdAt: '2021-04-20',
        title: 'Perbaikan Jalan',
        img: require('../../../assets/img/projects_dummy/1.jpeg'),
        likes: 20,
        status: 'unverified',
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        solution: 7,
        contributors: 3
    },
    {
        id: 2,
        name: 'Badarawuhi',
        location: 'Jalan Kaliurang',
        createdAt: '2021-04-15',
        title: 'Perbaikan Desa Penari',
        img: require('../../../assets/img/projects_dummy/2.jpeg'),
        likes: 11,
        status: 'unverified',
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        solution: 4,
        contributors: 4
    },
    {
        id: 3,
        name: 'Mba Andini',
        location: 'Jalan Palagan',
        createdAt: '2021-04-23',
        title: 'Tambang Emas untuk Saham',
        img: require('../../../assets/img/projects_dummy/3.jpeg'),
        likes: 11,
        status: 'unverified',
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        solution: 10,
        contributors: 7
    },
    {
        id: 4,
        name: 'Dewa AC',
        location: 'Jalan in Aja Dulu',
        createdAt: '2021-04-27',
        title: 'Rekonstruksi Pos Ronda',
        img: require('../../../assets/img/projects_dummy/4.jpeg'),
        likes: 100,
        status: 'unverified',
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        solution: 15,
        contributors: 12
    },
    {
        id: 5,
        name: 'Dewa Bujangan',
        location: 'Jalan yang kau pilih',
        createdAt: '2021-04-22',
        title: 'Move On dari Jalan Ini',
        img: require('../../../assets/img/projects_dummy/5.jpeg'),
        likes: 2,
        status: 'rejected',
        desc: 'Patah hatiku',
        solution: 15,
        contributors: 12
    },
    {
        id: 6,
        name: 'Nynyirmen',
        location: 'Jilin Kiliiring',
        createdAt: '2021-04-22',
        title: 'Pirbiikin jilin kiliiring',
        img: require('../../../assets/img/projects_dummy/6.jpeg'),
        likes: 2,
        status: 'rejected',
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        solution: 15,
        contributors: 12
    },
    {
        id: 7,
        name: 'Karmi Ikhlas',
        location: 'Bundaran HI',
        createdAt: '2021-04-22',
        title: 'Pengkotakan Bundaran HI',
        img: require('../../../assets/img/projects_dummy/3.jpeg'),
        likes: 2,
        status: 'unverified',
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        solution: 15,
        contributors: 12
    },
]