export default [
    'Economic and Business',
    'Law',
    'Medical',
    'Engineering',
    'Architecture',
    'Liberal Arts',
    'Literature and Culture',
    'Agricultire',
    'Education',
    'Political Science',
    'Aplied Science',
    'Hospitality and Tourism',
    'Psychology',
    'Others',
]