export default [
    { label: 'Accounting, banking or finance', value: 'Accounting, banking or finance' },
    { label: 'Business, consultancy or management', value: 'Business, consultancy or management' },
    { label: 'Charity and voluntary work', value: 'Charity and voluntary work' },
    { label: 'Creative arts or design', value: 'Creative arts or design' },
    { label: 'Energy and utilities', value: 'Energy and utilities' },
    { label: 'Engineering or manufacturing', value: 'Engineering or manufacturing' },
    { label: 'Environment or agriculture', value: 'Environment or agriculture' },
    { label: 'Healthcare', value: 'Healthcare' },
    { label: 'Hospitality or events', value: 'Hospitality or events' },
    { label: 'Computing or IT', value: 'Computing or IT' },
    { label: 'Law', value: 'Law' },
    { label: 'Law enforcement and security', value: 'Law enforcement and security' },
    { label: 'Leisure, sport or tourism', value: 'Leisure, sport or tourism' },
    { label: 'Marketing, advertising or PR', value: 'Marketing, advertising or PR' },
    { label: 'Media or digital', value: 'Media or digital' },
    { label: 'Property or construction', value: 'Property or construction' },
    { label: 'Public services or administration', value: 'Public services or administration' },
    { label: 'Recruitment or HR', value: 'Recruitment or HR' },
    { label: 'Retail', value: 'Retail' },
    { label: 'Sales', value: 'Sales' },
    { label: 'Science or pharmaceuticals', value: 'Science or pharmaceuticals' },
    { label: 'Social care', value: 'Social care' },
    { label: 'Education or teacher training', value: 'Education or teacher training' },
    { label: 'Transport or logistics', value: 'Transport or logistics' },
]