@domain = {{$dotenv HOST}}

###
# @name a
POST {{domain}}/api/auth/login
Content-Type: application/json

{
    "email": "gabri.ns@gmail.com",
    "password": "12345678"
}


###
# @name apiLogin
POST {{domain}}/api/auth/login
Content-Type: application/json

{
    "email": "gabri.ns@gmail.com",
    "password": "12345678"
}

###
GET {{domain}}/api/v1/overtimes/today
Authorization: Bearer {{apiLogin.response.body.$.session_id}}
