@domain = {{$dotenv HOST}}

###
# @name apiLogin
POST {{domain}}/api/auth/login
Content-Type: application/json

{
    "email": "gabri.ns@gmail.com",
    "password": "12345678"
}





###
# @name skillana
GET https://skillana.widyaskilloka.com/api/v1/user-detail?email=amalianurlita97@gmail.com
Authorization: Apikey {{$dotenv SKILLANA_API_KEY}}






###
# @name apiGetAllVacancies
GET {{domain}}/api/v1/recruitment/vacancies
Authorization: Bearer {{apiLogin.response.body.$.session_id}}



###
# @name apiGetDetailVacancies
GET {{domain}}/api/v1/recruitment/vacancies/36
Authorization: Bearer {{apiLogin.response.body.$.session_id}}





###
# @name apiGetAllApplicants
GET {{domain}}/api/v1/recruitment/applicants?
    ?status=unprocessed
Authorization: Bearer {{apiLogin.response.body.$.session_id}}



###
# @name apiGetDetailApplicant
GET {{domain}}/api/v1/recruitment/applicants/44
Authorization: Bearer {{apiLogin.response.body.$.session_id}}







###
# @name downloadProfile
GET https://skillana.widyaskilloka.com/api/v1/users/download_profile/46


